#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelerometerZ, sensorAccelerometer)
#pragma config(Sensor, in3,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in4,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in5,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarInput,     sensorSONAR_inch)
#pragma config(Sensor, dgtl8,  enableAuton,    sensorTouch)
#pragma config(Sensor, dgtl9,  arcadeFlag,     sensorTouch)
#pragma config(Sensor, dgtl10, lowerLift,      sensorTouch)
#pragma config(Sensor, dgtl11, flag2,          sensorTouch)
#pragma config(Sensor, dgtl12, flag3,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBase,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBase,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*
 * compare(valueOne, valueTwo)
 *
 * Compare two numbers. Returns:
 *   -1 if valueOne is less than valueTwo
 *    0 if valueOne is equal to valueTwo
 *    1 if valueOne is greater than to valueTwo
 *
 * Equivelant to the following code, but is
 * branchless, resulting in zero jumps in the
 * assembled code:
 *    if (valueOne < valueTwo) {
 *      return -1;
 *    } else if (valueOne > valueTwo) {
 *      return 1;
 *    } else {
 *      return 0;
 *    }
 *
 * Uses the concept that a boolean "true" value
 * is equivelant to "1" and a boolean "false" value
 * is equivalant to "0".
 */
int compare(int valueOne, int valueTwo) {
	return (valueOne > valueTwo) - (valueOne < valueTwo);
}

/*
 * getChannel(value)
 * getChannel(value, threshold)
 *
 * Return the value of a channel, thresholded to a certain value
 */
int getChannel(TVexJoysticks value, int threshold = 20) {
	return fabs(vexRT[value]) > threshold ? vexRT[value] : 0;
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void setupMotors() {
	// Slave the right side together
	slaveMotor(rightBaseOne, RightBase);
	slaveMotor(rightBaseThree, RightBase);

	// Slave the left side together
	slaveMotor(leftBaseOne, LeftBase);
	slaveMotor(leftBaseThree, LeftBase);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, Lift);
	slaveMotor(leftBottomLift, Lift);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
   // Set up the motor assemblies as slaves, for use in autonomous and
	// driver control.
	setupMotors();
}

void driveBase(int speed, int encoderValue) {
	int encoder = 0;
	motor[RightBase] = speed;
	motor[LeftBase] = speed;
	nMotorEncoder[LeftBase] = 0;
	nMotorEncoder[RightBase] = 0;
	//while ((nMotorEncoder[LeftBase] + nMotorEncoder[RightBase]) / 2 < encoderValue) {
	while(nMotorEncoder[LeftBase] < encoderValue) {
		encoder = nMotorEncoder[LeftBase];
		switch (compare(nMotorEncoder[LeftBase], nMotorEncoder[RightBase])) {
			case -1:
				// Right base is ahead; speed the left base up
				motor[LeftBase] = speed + 10;
				motor[RightBase] = speed;
				break;
			case 1:
				// Left base is ahead; speed the right base up
				motor[LeftBase] = speed;
				motor[RightBase] = speed + 10;
				break;
			default:
				// Set both to the default speed
				motor[LeftBase] = motor[RightBase] = speed;
				break;
		}
	}
	motor[RightBase] = 0;
	motor[LeftBase] = 0;

}

void turnLeft(int speed, int degrees10) {
	int error = 5;
	while(abs(SensorValue[gyro]) > degrees10 + error || abs(SensorValue[gyro]) < degrees10 - error) {
		motor[RightBase] = speed;
		motor[LeftBase]  = -speed;
	}
	motor[RightBase] = 0;
	motor[LeftBase]  = 0;
}

void turnRight(int speed, int degrees10) {
	int error = 5;
	while(abs(SensorValue[gyro]) > degrees10 + error || abs(SensorValue[gyro]) < degrees10 - error) {
		motor[RightBase] = -speed;
		motor[LeftBase]  = speed;
	}
	motor[RightBase] = 0;
	motor[LeftBase]  = 0;
}

void driveLift(int speed, int time) {
	motor[Lift] = speed;
	wait1Msec(time);
	motor[Lift] = 0;
}
void driveClaw(int speed, int time) {
	motor[Claw] = speed;
	wait1Msec(time);
}

/*
 * startTask(autonomous)
 *
 * The autonomous task for the competition. Currently contains code
 * that relies on timing, but there are plans to make it more reliable
 * using a combination of encoders, line sensors/ultrasonic sensors, and
 * the gyro.
 */
task autonomous() {
	driveLift(127, 500);
	// Kill switch: Remove the jumper on pin 9 to lower lift
	if (SensorValue[lowerLift]) {
		motor[Lift] = -63;
		wait1Msec(1500);
		motor[Lift] = 0;
		return;
	}
	// Kill switch: Remove the jumper on pin 8 to disable auton
	if (!SensorValue[enableAuton]) return;
	// Autonomous: Grab the cone and place it on the mobile goal.
	// Calibrate gyro (AKA: Reset to zero)
	SensorType[gyro] = sensorNone;
	wait1Msec(200);
	SensorType[gyro] = sensorGyro;
//	wait1Msec(2000);

	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program
	if(SensorValue(sonarInput != -1)){
		while(SensorValue(sonarInput) > 3 )		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
		{                                                                         // || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
			motor[RightBase] = 127;			// Motor on port2 is run at half (63) power forward
			motor[LeftBase]  = 127;			// Motor on port3 is run at half (63) power forward
		}
		motor[RightBase] = 0;				//we are close enough.  Stop the motors
		motor[LeftBase] = 0;
	}
	driveLift(-127, 300);
	driveClaw(127, 420);
  //Clear the encoders associated with the left and right motors
	nMotorEncoder[RightBase] = 0;
	nMotorEncoder[LeftBase] = 0;

	//While less than 1000 encoder counts of the right and left motors
//	while(nMotorEncoder[RightBase] > -1000)
	resetMotorEncoder(LeftBase);
	resetMotorEncoder(RightBase);
	while(nMotorEncoder[LeftBase] > -1000 & nMotorEncoder[RightBase] > -1000)
	{
		//Move in reverse at full power
		motor[RightBase] = -127;
		motor[LeftBase]	= -127;
	}

}
/*
 * startTask(usercontrol());
 *
 * User control code for the competition. This runs when in "Driver" Control
 */
task usercontrol()
{
	// Loop forever
  while (true)
  {
  	// Joystick 1 - Arcade Control (Dual Joystick)
  	if (SensorValue[arcadeFlag]) {
  		motor[LeftBase]  = getChannel(Ch3) + getChannel(Ch1); // Left Side
  		motor[RightBase] = getChannel(Ch3) - getChannel(Ch1); // Right Side
  	} else {
  		motor[LeftBase]  = getChannel(Ch3); // Left Side
  		motor[RightBase] = getChannel(Ch2); // Right Side
  	}

  	// Joystick 2 - Lift/Claw control (Shoulder Buttons)
  	motor[Claw] = compare(vexRT[Btn5UXmtr2], vexRT[Btn5DXmtr2]) * 127;
  	motor[Lift] = compare(vexRT[Btn6UXmtr2], vexRT[Btn6DXmtr2]) * 127;
  }
}
