#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelerometerZ, sensorAccelerometer)
#pragma config(Sensor, in3,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in4,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in5,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarInput,     sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  disableAuton,   sensorDigitalIn)
#pragma config(Sensor, dgtl9,  flag1,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, flag2,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, flag3,          sensorDigitalIn)
#pragma config(Sensor, dgtl12, flag4,          sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightBaseTwo,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTopLift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftBaseTwo,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Common includes for functions
#include "common.c"

// Include the autonomous recorder/playback library
#include "autonRecorder.c"

// Definitions to make the code more readable when referencing
// an assembly on the robot
#define LeftBase leftBaseTwo // The main left base motor.
#define RightBase rightBaseTwo // The main right base motor.
#define Lift rightTopLift // A lift motor.
#define Claw clawMotor // A claw motor.

/*
 * setupMotors()
 *
 * Sets up all the motors for the robot.
 * This includes slaving together multiple physical motor
 * mechanisms from the robot together
 */
void setupMotors() {
	// Slave the right side together
	slaveMotor(rightBaseOne, rightBaseTwo);
	slaveMotor(rightBaseThree, rightBaseTwo);

	// Slave the left side together
	slaveMotor(leftBaseOne, leftBaseTwo);
	slaveMotor(leftBaseThree, leftBaseTwo);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, rightTopLift);
	slaveMotor(leftBottomLift, rightTopLift);
}

/*
 * Pre-Autonomous code
 *
 * Set up the sensors needed for autonomous,
 * as well as set up an autonomous selector
 * on the LCD.
 */
int auton; // Used to store selected autonomous (0 for no autonomous)
void pre_auton()
{
	string AutonModes[] = {
		"No Autonomous",
		"Autonomous 1",
	};
	int currentSelection = 0;
	int autonomousLength = 3;
  // Stop user created tasks between Autonomous and Driver controlled modes.
  bStopTasksBetweenModes = true;

	// Take control of the LCD
	bDisplayCompetitionStatusOnLcd = false;

  // Set up the motor assemblies as slaves, for use in autonomous and
	// driver control.
	setupMotors();

	// Set up the arcade control settings for dual joysticks on the main
	// controller, and pass the left and  right base motors as parameters
	setupArcadeControl(DualJoystick, LeftBase, RightBase);
	clearTimer(T1);
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true; // Turn on LCD Backlight, since we are in use
	displayLCDCenteredString(0, AutonModes[currentSelection]);
	displayLCDCenteredString(1, " <   Select   > ");
	if (!SensorValue[disableAuton]) {
		while (!lcdButtonPressed(LCDCenterButton)) {
			waitForLCDPress();
			if (lcdButtonPressed(LCDLeftButton)) {
				// Left button pressed
				currentSelection = (currentSelection - 1) % autonomousLength;
				displayLCDCenteredString(0, AutonModes[currentSelection]);
				waitForRelease(LCDAnyButton);
			} else if (lcdButtonPressed(LCDRightButton)) {
				// Right button pressed
				currentSelection = (currentSelection + 1) % autonomousLength;
				clearLCDLine(0);
				displayLCDCenteredString(0, AutonModes[currentSelection]);
				waitForRelease(LCDAnyButton);
			}
		}
		auton = currentSelection;
	}
}

task openClaw() {
	motor[Claw] = 127;
	wait1Msec(420);
	motor[Claw] = 0;
}

void closeClaw() {
	motor[Claw] = -127;
	wait1Msec(420);
	motor[Claw] = 0;
}

task autonomous() {
	if (auton == 0 || SensorValue[disableAuton]) return; // No auton, possibly with kill switch
	// Current time breakdown:
	// 900 ms			Used for claw opening/close		Can be separated into tasks for opening only
	// *** ms			Used for driving base/encoder	Can NOT be separated into tasks
	startTask(openClaw); // Separate task to do that while starting the driving itself
	driveForward(58.7, LeftBase, RightBase); // Drive to cone
	closeClaw(); // Grab cone
	driveBackward(45, LeftBase, RightBase); // Back up until a good distance to turn from
	turnDegrees(165, LeftBase, RightBase, gyro); // Turn 165 degrees (face target)
	driveForward(50, LeftBase, RightBase);
	startTask(openClaw);
}

/*
 * User control code.
 *
 * Controls:
 *   Main Controller:
 *     Left Joystick - Left Base
 *     Right Joystick - Right Base
 *     Button 5U - Lift Up
 *     Button 5D - Lift Down
 */
task usercontrol() {
	setupMotors();
	startTask(autonomous);
	//while (true) {} // Let's stop here... I'd rather not go through the trouble of doing anything  else.
	startTask(arcadeControl);
  while (true)
  {
		//motor[LeftBase] = getValueOf(Ch3);
		//motor[RightBase] = getValueOf(Ch2);
		motor[Lift] = getButtonChannel(Btn6Xmtr2, 127);
		motor[Claw] = getButtonChannel(Btn5Xmtr2, 127);
  }
}
