#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelerometerZ, sensorAccelerometer)
#pragma config(Sensor, in3,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in4,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in5,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarInput,     sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  enableAuton,    sensorTouch)
#pragma config(Sensor, dgtl9,  arcadeFlag,     sensorTouch)
#pragma config(Sensor, dgtl10, redFlag,        sensorTouch)
#pragma config(Sensor, dgtl11, flag2,          sensorTouch)
#pragma config(Sensor, dgtl12, flag3,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBase,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBase,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float oneInch = 50.52; // One inch, for measurements pertaining to
int error = 3;

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

/*
 * compare(valueOne, valueTwo)
 *
 * Compare two numbers. Returns:
 *   -1 if valueOne is less than valueTwo
 *    0 if valueOne is equal to valueTwo
 *    1 if valueOne is equal to valueTwo
 *
 * Equivelant to the following code, but is
 * branchless, resulting in zero jumps in the
 * assembled code:
 *    if (valueOne < valueTwo) {
 *      return -1;
 *    } else if (valueOne > valueTwo) {
 *      return 1;
 *    } else {
 *      return 0;
 *    }
 *
 * Uses the concept that a boolean "true" value
 * is equivelant to "1" and a boolean "false" value
 * is equivalant to "0".
 */
int compare(int valueOne, int valueTwo) {
	return (valueOne > valueTwo) - (valueOne < valueTwo);
}

void setupMotors() {
	// Slave the right side together
	slaveMotor(rightBaseOne, RightBase);
	slaveMotor(rightBaseThree, RightBase);

	// Slave the left side together
	slaveMotor(leftBaseOne, LeftBase);
	slaveMotor(leftBaseThree, LeftBase);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, Lift);
	slaveMotor(leftBottomLift, Lift);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
   // Set up the motor assemblies as slaves, for use in autonomous and
	// driver control.
	setupMotors();
}

void driveBase(int speed, int time) {
	motor[RightBase] = speed;
	motor[LeftBase] = speed;
	wait1Msec(time);
	motor[RightBase] = 0;
	motor[LeftBase] = 0;
}

/*
 * driveBaseEncoders(speed, distance)
 *
 * Drives the base the specified distance, taking into account
 * encoder position and making sure that we don't overshoot or
 * drift to one side (should fix the issue if we ever accidentally
 * use speed motors instead of torque again.
 */
void driveBaseEncoders(int speed, float distance) {
	int initialGyro = SensorValue[gyro];
	int encoderValue = distance * oneInch;
	nMotorEncoder[LeftBase] = nMotorEncoder[RightBase] = 0;
	while (!(abs(SensorValue[accelerometerX]) > 1)) {
		motor[LeftBase] = motor[RightBase] = speed;
	}
	while (abs(nMotorEncoder[LeftBase]) < encoderValue) {
		switch (SensorValue[gyro] - initialGyro) {
			case -1:
				// LeftBase is lagging
				motor[LeftBase] = speed + 10;
				motor[RightBase] = speed;
				break;
			case 1:
				// RightBase is lagging
				motor[LeftBase] = speed;
				motor[RightBase] = speed + 10;
				break;
			default:
				// Equal; good speed
				motor[LeftBase] = speed;
				motor[RightBase] = speed;
		}
	}
	motor[LeftBase] = 0;
	motor[RightBase] = 0;
}

/*
 * Turn the robot,  with the specified values for the
 * right base and left base (in that order). The third
 * argument is the amount of time that the motors will
 * run for
 */
void turn(int speed, int reverse, int time) {
	motor[RightBase] = speed;
	motor[LeftBase] = reverse;
	wait1Msec(time);
	motor[RightBase] = 0;
	motor[LeftBase] = 0;
}

/*
 * Turn the robot, with the specified values for the speed
 * and number of degrees (times ten) to turn. Make sure that
 * we use the gyro correctly (also, TODO: Slight reverse at
 * end to force stop the robot)
 */
void turnDegreesRight(int speed, int degrees10) {
	while(abs(SensorValue[gyro]) > degrees10 + error || abs(SensorValue[gyro]) < degrees10 - error)
  {
    if(abs(SensorValue[gyro]) > degrees10)
    {
      motor[RightBase] = -50;
      motor[LeftBase]  = 50;
    }
    else
    {
      motor[RightBase] = 50;
      motor[LeftBase] = -50;
    }
  }
}

void turnDegreesLeft(int speed, int degrees10) {
	while(abs(SensorValue[gyro]) > degrees10 + error || abs(SensorValue[gyro]) < degrees10 - error)
  {
    if(abs(SensorValue[gyro]) > degrees10)
    {
      motor[RightBase] = 50;
      motor[LeftBase]  = -50;
    }
    else
    {
      motor[RightBase] = -50;
      motor[LeftBase]  = 50;
    }
  }
}

void driveLift(int speed, int time) {
	motor[Lift] = speed;
	wait1Msec(time);
	motor[Lift] = 0;
}
void driveClaw(int speed, int time) {
	motor[Claw] = speed;
	wait1Msec(time);
	motor[Claw] = 0;
}

/*
 * startTask(autonomous)
 *
 * The autonomous task for the competition. Uses the accelerometer,
 * gyro, motor encoders, and ultrasonic. Also contains code, at
 * the moment, that relies on timing for the claw and lift, but
 * there are plans to make it more reliable using motor encoders.
 * Additionally, line sensors are planned to be used for accurately
 * reaching the mobile goal
 */
task autonomous() {
	// Kill switch: Remove the jumper on pin 8 to disable auton
	if (!SensorValue[enableAuton]) return;
	// Autonomous: Grab the cone and place it on the mobile goal.
	SensorType[gyro] = sensorNone;
	wait1Msec(200);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000); // Gyro init
	// Lift up arm initially
	driveLift(127, 800);
	// Move forward, and then quickly backwards, and then stop for inertia to open the claw
	// Use either the ultrasonic (if available), or fallback to encoders
	if (SensorValue[sonarInput] != -1){
		// Ultrasonic is available; use that to grab the cone
		while (SensorValue(sonarInput) > 12) {
			motor[RightBase] = 63;			// Motor on port2 is run at half (63) power forward
			motor[LeftBase]  = 63;			// Motor on port3 is run at half (63) power forward
		}
	} else {
		// No ultrasonic/not working; fallback to encoders
		driveBaseEncoders(127, 8.2);
	}
	motor[LeftBase] = motor[RightBase] = -127;
	wait1Msec(100);
	motor[LeftBase] = motor[RightBase] = 0;
	// Wait time for the claw to finish falling
	wait1Msec(1000);
	// Close the claw on the cone
	motor[Claw] = -127;
	wait1Msec(500);
	motor[Claw] = -63;
	// Lift the arm enough to be able to move to the mobile goal
	driveLift(127, 2700);
	// Back up a little bit
	driveBase(-127, 300);
	// Turn to face the mobile goal
	int turnDegrees = 209; // 18.0 degrees
	if (SensorValue[redFlag]) {
		turnDegreesLeft(127, turnDegrees);
	} else {
		turnDegreesRight(127, turnDegrees);
	}
	// Reach the mobile goal
 	driveBaseEncoders(96, 23.2);
 	motor[LeftBase] = motor[RightBase] = -127;
 	wait1Msec(150);
 	motor[LeftBase] = motor[RightBase] = 0;
	// Lower the arm onto the mobile goal
	driveLift(-127, 800);
	// Release the cone
	driveClaw(127, 420);
}

/*
 * getChannel(value)
 * getChannel(value, threshold)
 *
 * Return the value of a channel, thresholded to a certain value
 */
int getChannel(TVexJoysticks value, int threshold = 20) {
	return fabs(vexRT[value]) > threshold ? vexRT[value] : 0;
}

/*
 * startTask(usercontrol());
 *
 * User control code for the competition. This runs when in "Driver" Control
 * Current controls:
 *   With pin 9 (arcadeFlag) in:
 *     Arcade control using y axis from left joystick on main controller, and x axis from the right joystick
 *   With pin 9 (arcadeFlag) out:
 *     Tank Drive on main controller
 *   Button 5U - Open claw
 *   Button 5D - Close claw
 *   Button 6U - Raise Lift
 *   Button 6D - Lower Lift
 */
task usercontrol()
{
	// Loop forever
  while (true)
  {
  	// Joystick 1 - Arcade Control (Dual Joystick)
  	if (SensorValue[arcadeFlag]) {
  		motor[LeftBase]  = getChannel(Ch3) + getChannel(Ch1); // Left Side
  		motor[RightBase] = getChannel(Ch3) - getChannel(Ch1); // Right Side
  	} else {
  		motor[LeftBase]  = getChannel(Ch3); // Left Side
  		motor[RightBase] = getChannel(Ch2); // Right Side
  	}

  	// Joystick 2 - Lift/Claw control (Shoulder Buttons)
  	motor[Claw] = compare(vexRT[Btn5UXmtr2], vexRT[Btn5DXmtr2]) * 127;
  	motor[Lift] = compare(vexRT[Btn6UXmtr2], vexRT[Btn6DXmtr2]) * 127;
  }
}
