#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelerometerZ, sensorAccelerometer)
#pragma config(Sensor, in3,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in4,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in5,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarInput,     sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  enableAuton,    sensorTouch)
#pragma config(Sensor, dgtl9,  arcadeFlag,     sensorTouch)
#pragma config(Sensor, dgtl10, recordAuton,       sensorTouch)
#pragma config(Sensor, dgtl11, flag2,          sensorTouch)
#pragma config(Sensor, dgtl12, flag3,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBase,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBase,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void setupMotors() {
	// Slave the right side together
	slaveMotor(rightBaseOne, RightBase);
	slaveMotor(rightBaseThree, RightBase);

	// Slave the left side together
	slaveMotor(leftBaseOne, LeftBase);
	slaveMotor(leftBaseThree, LeftBase);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, Lift);
	slaveMotor(leftBottomLift, Lift);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
   // Set up the motor assemblies as slaves, for use in autonomous and
	// driver control.
	setupMotors();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous()
{
  /*
   * Assume that the preload is placed in a way that allows pushing it forward,
   * moving backwards, and being able to pick it up from there.
   * -127 opens the claw, right?
   * There are encoders on the left base, right base, and the lift assemblies
   * We are assuming that the IMEs are in a working order on 393 motor
   * Currently untested. Hope to get this working quickly
   */
   float wheelDiameter = 4.0; // 4.0 inch wheel diameter
   float wheelCircumference = PI * wheelDiameter; // Circumference of the wheel
   float encoderPerRotation = 627.2; // Encoder counts per one full rotation
   float oneFoot = (encoderPerRotation / wheelCircumference) * 12;
   int baseSpeed = 100;
   // Raise lift and open the claw
   nMotorEncoder[Lift] = 0;
   moveMotorTarget(Lift, 1400, baseSpeed);
   while(!getMotorTargetCompleted(Lift))
     sleep(10);
   motor[Claw] = -127;
   wait1Msec(420);
   motor[Claw] = 0;
   // Move forward until the line (roughly)
   nMotorEncoder[LeftBase] = nMotorEncoder[RightBase] = 0; // Reset encoders for the base
   moveMotorTarget(LeftBase, oneFoot * 1.9, baseSpeed);
   moveMotorTarget(RightBase, oneFoot * 1.9, baseSpeed);
   while (!(getMotorTargetCompleted(LeftBase) && getMotorTargetCompleted(RightBase)))
     sleep(10);
   // Here, there is a break, because on the field, there is a line. It could be used
   // for the autonomous, but due to issues with the robot, there was an inability to
   // test the robot, and not including code to handle a line sensor makes sure that,
   // for the time being, we are using code that we know will work as expected
   nMotorEncoder[LeftBase] = nMotorEncoder[RightBase] = 0; // Reset encoders for the base
   moveMotorTarget(LeftBase, oneFoot * 1.9, baseSpeed);
   moveMotorTarget(RightBase, oneFoot * 1.9, baseSpeed);
   while (!(getMotorTargetCompleted(LeftBase) && getMotorTargetCompleted(RightBase)))
     sleep(10);
   // Move lift down, and open claw
   nMotorEncoder[Lift] = 0;
   moveMotorTarget(Lift, -1000, baseSpeed * -1);
   while(!getMotorTargetCompleted(Lift))
     sleep(10);
   motor[Claw] = -127;
   wait1Msec(420);
   motor[Claw] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

/*
 * compare(valueOne, valueTwo)
 *
 * Compare two numbers. Returns:
 *   -1 if valueOne is less than valueTwo
 *    0 if valueOne is equal to valueTwo
 *    1 if valueOne is equal to valueTwo
 *
 * Equivelant to the following code, but is
 * branchless, resulting in zero jumps in the
 * assembled code:
 *    if (valueOne < valueTwo) {
 *      return -1;
 *    } else if (valueOne > valueTwo) {
 *      return 1;
 *    } else {
 *      return 0;
 *    }
 *
 * Uses the concept that a boolean "true" value
 * is equivelant to "1" and a boolean "false" value
 * is equivalant to "0".
 */
int compare(int valueOne, int valueTwo) {
	return (valueOne > valueTwo) - (valueOne < valueTwo);
}

task usercontrol()
{
	// Loop forever
  while (true)
  {
  	// Joystick 1 - Arcade Control (Dual Joystick)
  	motor[LeftBase] = vexRT[Ch3] + vexRT[Ch1]; // Left Side
  	motor[RightBase] = vexRT[Ch3] - vexRT[Ch1]; // Right Side

  	// Joystick 2 - Lift/Claw control (Shoulder Buttons)
  	motor[Claw] = compare(vexRT[Btn5U], vexRT[Btn5D]) * 127;
  	motor[Lift] = compare(vexRT[Btn6U], vexRT[Btn6D]) * 127;
  }
}
