#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelerometerZ, sensorAccelerometer)
#pragma config(Sensor, in3,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in4,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in5,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarInput,     sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  enableAuton,    sensorTouch)
#pragma config(Sensor, dgtl9,  arcadeFlag,     sensorTouch)
#pragma config(Sensor, dgtl10, recordAuton,       sensorTouch)
#pragma config(Sensor, dgtl11, flag2,          sensorTouch)
#pragma config(Sensor, dgtl12, flag3,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBase,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBase,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setupMotors() {
	// Slave the right side together
	slaveMotor(rightBaseOne, RightBase);
	slaveMotor(rightBaseThree, RightBase);

	// Slave the left side together
	slaveMotor(leftBaseOne, LeftBase);
	slaveMotor(leftBaseThree, LeftBase);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, Lift);
	slaveMotor(leftBottomLift, Lift);
}

task main() {
	// Systems Check
	setupMotors();
	motor[LeftBase] = 127;
	motor[RightBase] = 127;
	sleep(500);
	motor[LeftBase] = -127;
	motor[RightBase] = -127;
	sleep(500);
	motor[LeftBase] = -127;
	motor[RightBase] = 127;
	sleep(500);
	motor[LeftBase] = 127;
	motor[RightBase] = -127;
	sleep(500);
	motor[LeftBase] = 0;
	motor[RightBase] = 0;
	motor[Claw] = 63;
	sleep(420);
	motor[Claw] = -63;
	sleep(420);
	motor[Claw] = 0;
	motor[Lift] = 127;
	sleep(500);
	motor[Lift] = -127;
	sleep(500);
	motor[Lift] = 0;
}
